export const CHANGE_FIELD = 'CHANGE_FIELD';
export type CHANGE_FIELD = typeof CHANGE_FIELD;

export const GET_SERVICE = 'GET_SERVICE';
export type GET_SERVICE = typeof GET_SERVICE;
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL';

export const GET_ORDERSTATE = 'GET_ORDERSTATE';
export type GET_ORDERSTATE = typeof GET_ORDERSTATE;
export const GET_ORDERSTATE_SUCCESS = 'GET_ORDERSTATE_SUCCESS';
export const GET_ORDERSTATE_FAIL = 'GET_ORDERSTATE_FAIL';

export const GET_RULES = 'GET_RULES';
export type GET_RULES = typeof GET_RULES;
export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const GET_RULES_FAIL = 'GET_RULES_FAIL';

export const SAVE_STRATEGYRULE = 'SAVE_STRATEGYRULE';
export type SAVE_STRATEGYRULE = typeof SAVE_STRATEGYRULE;
export const SAVE_STRATEGYRULE_SUCCESS = 'SAVE_STRATEGYRULE_SUCCESS';
export const SAVE_STRATEGYRULE_FAIL = 'SAVE_STRATEGYRULE_FAIL';