export const CHANGE_FIELD = 'CHANGE_FIELD';
export type CHANGE_FIELD = typeof CHANGE_FIELD;

export const GET_SERVICE = 'GET_SERVICE';
export type GET_SERVICE = typeof GET_SERVICE;
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL';

export const GET_ORDERSTATE = 'GET_ORDERSTATE';
export type GET_ORDERSTATE = typeof GET_ORDERSTATE;
export const GET_ORDERSTATE_SUCCESS = 'GET_ORDERSTATE_SUCCESS';
export const GET_ORDERSTATE_FAIL = 'GET_ORDERSTATE_FAIL';

export const GET_RULES = 'GET_RULES';
export type GET_RULES = typeof GET_RULES;
export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const GET_RULES_FAIL = 'GET_RULES_FAIL';

export const SAVE_STRATEGYRULE = 'SAVE_STRATEGYRULE';
export type SAVE_STRATEGYRULE = typeof SAVE_STRATEGYRULE;
export const SAVE_STRATEGYRULE_SUCCESS = 'SAVE_STRATEGYRULE_SUCCESS';
export const SAVE_STRATEGYRULE_FAIL = 'SAVE_STRATEGYRULE_FAIL';

export const GET_WHCHATPUSH = 'GET_WHCHATPUSH';
export type GET_WHCHATPUSH = typeof GET_WHCHATPUSH;
export const GET_WHCHATPUSH_SUCCESS = 'GET_WHCHATPUSH_SUCCESS';
export const GET_WHCHATPUSH_FAIL = 'GET_WHCHATPUSH_FAIL';

export const SAVE_RULE = 'SAVE_RULE';
export type SAVE_RULE = typeof SAVE_RULE;
export const SAVE_RULE_SUCCESS = 'SAVE_RULE_SUCCESS';
export const SAVE_RULE_FAIL = 'SAVE_RULE_FAIL';

export const SAVE_MODEL = 'SAVE_MODEL';
export type SAVE_MODEL = typeof SAVE_MODEL;

export const CHANGE_SRDC = 'CHANGE_SRDC';
export type CHANGE_SRDC = typeof CHANGE_SRDC;

export const RESET_WECHATPUSH = 'RESET_WECHATPUSH';

export const GET_HOMEPAGECOUNT = 'GET_HOMEPAGECOUNT';
export type GET_HOMEPAGECOUNT = 'GET_HOMEPAGECOUNT';

export const GET_RESPONSIBLE = 'GET_RESPONSIBLE';
export type GET_RESPONSIBLE = 'GET_RESPONSIBLE';

export const GET_HOME_PAGE_COUNT_SUCCESS = 'GET_HOME_PAGE_COUNT_SUCCESS';
export type GET_HOME_PAGE_COUNT_SUCCESS = typeof GET_HOME_PAGE_COUNT_SUCCESS;

export const GET_RESPONSIBLE_SUCCESS = 'GET_RESPONSIBLE_SUCCESS';
export type GET_RESPONSIBLE_SUCCESS = 'GET_RESPONSIBLE_SUCCESS';

export const GET_RESPONSIBLE_FAIL = 'GET_RESPONSIBLE_FAIL';
export type GET_RESPONSIBLE_FAIL = 'GET_RESPONSIBLE_FAIL';

export const GET_HOME_PAGE_COUNT_FAIL = 'GET_HOME_PAGE_COUNT_FAIL';
export type GET_HOME_PAGE_COUNT_FAIL = typeof GET_HOME_PAGE_COUNT_FAIL;