export const STRATEGYRULE = 'STRATEGYRULE';
export type STRATEGYRULE = typeof STRATEGYRULE;

export const STRATEGY_RULE_SUCCESS = 'STRATEGY_RULE_SUCCESS';
export type STRATEGY_RULE_SUCCESS = typeof STRATEGY_RULE_SUCCESS;

export const STRATEGY_RULE_FAIL = 'STRATEGY_RULE_FAIL';
export type STRATEGY_RULE_FAIL = typeof STRATEGY_RULE_FAIL;

export const RESPERSONRULE = 'RESPERSONRULE';
export type RESPERSONRULE = typeof RESPERSONRULE;

export const RES_PERSON_RULE_SUCCESS = 'RES_PERSON_RULE_SUCCESS';
export type RES_PERSON_RULE_SUCCESS = typeof RES_PERSON_RULE_SUCCESS;

export const RES_PERSON_RULE_FAIL = 'RES_PERSON_RULE_FAIL';
export type RES_PERSON_RULE_FAIL = typeof RES_PERSON_RULE_FAIL;