
export const DETAILORDER_STRATEGY = 'DETAILORDER_STRATEGY';
export type DETAILORDER_STRATEGY = typeof DETAILORDER_STRATEGY;

export const ONSAVERULE = 'ONSAVERULE';
export type ONSAVERULE = typeof ONSAVERULE;

export const DETAILORDER_STRATEGY_SUCCESS = 'DETAILORDER_STRATEGY_SUCCESS';
export type DETAILORDER_STRATEGY_SUCCESS = typeof DETAILORDER_STRATEGY_SUCCESS;

export const DETAILORDER_STRATEGY_FAIL = 'DETAILORDER_STRATEGY_FAIL';
export type DETAILORDER_STRATEGY_FAIL = typeof DETAILORDER_STRATEGY_FAIL;

export const ONSAVERULE_SUCCESS = 'ONSAVERULE_SUCCESS';
export type ONSAVERULE_SUCCESS = typeof ONSAVERULE_SUCCESS;

export const ONSAVERULE_FAIL = 'ONSAVERULE_FAIL';
export type ONSAVERULE_FAIL = typeof ONSAVERULE_FAIL;
