
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
// 获取列表事件名称
export const STRATEGY_LIST = 'STRATEGY_LIST';
export type STRATEGY_LIST = typeof STRATEGY_LIST;
// 获取列表事件－成功
export const STRATEGY_LIST_SUC = 'STRATEGY_LIST_SUC';
export type STRATEGY_LIST_SUC = typeof STRATEGY_LIST_SUC;
// 获取列表事件－失败
export const STRATEGY_LIST_FAIL = 'STRATEGY_LIST_FAIL';
export type STRATEGY_LIST_FAIL = typeof STRATEGY_LIST_FAIL;

// 同步修改输入框内容
export const CHANGE_PARAMS = 'CHANGE_PARAMS';
export type CHANGE_PARAMS = typeof CHANGE_PARAMS;
// 修改列表页页码数
export const CHANGE_PAGE = 'CHANGE_PAGE';
export type CHANGE_PAGE = typeof CHANGE_PAGE;